// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Item struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Capacity int32  `json:"capacity"`
}
