services:
  database:
    image: postgres:latest
    container_name: golang-be-template-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Manila
    ports:
      - 5432:${DB_PORT}
    expose:
      - 5432:${DB_PORT}
    networks:
      - default
    volumes:
      - pg-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  pg-data:
