name: CI

on:
  push:
    branches:
      - main
      - "feat/**"
      - "chore/**"
      - "fix/**"
      - "refactor/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.4

      - name: Verify dependencies
        run: go mod verify

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

      - name: Check for linting errors
        run: golangci-lint run
